# model name
model_name: SASRec

# hidden dimension
hidden_size: 1

# encoder hidden dimension
num_hidden_layers: 1

# todo: fill
initializer_range: 0.02

# todo: fill
num_attention_heads: 1

# todo: fill
hidden_act: gelu

# todo: fill
attention_probs_dropout_prob: 0.5

# todo: fill
hidden_dropout_prob: 0.5
