timestamp:
seed: 42
gpu_id: 0
no_cuda: false

# reserved keys (don't modify!)
cuda_condition:

defaults:
  - _self_
  - data: default.yaml
  - path: test.yaml
  - trainer: default.yaml
  - model: SASRec.yaml