# Basic Information
model: SRGNN # enter model name

# Training Hyper Parameters
epochs: 1
train_batch_size: 1024
eval_batch_size: 1024
learner: adam
learning_rate: 0.001
neg_sampling: 
eval_step: 1
stopping_step: 3 # threshold for early stopping
weight_decay: 0.0
loss_decimal_place: 4
train_neg_sample_args: 

#Evaluation Hyper Parameters:
metrics: ['Recall']
topk: [10]
valid_metric: Recall@10
valid_metric_bigger: True
metric_decimal_place: 4

# WandB Settings
log_wandb: True
wandb_project: 'MovieRec_recbole'
show_progress: True

# Paths
data_path: '../data'
output_path: 'outputs/'
submission_path: '../data/eval'

# DATA Settings
USER_ID_FIELD: user
ITEM_ID_FIELD: item
TIME_FIELD: time

load_col:
    inter: [user, item, time]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"
val_interval:
    time: "[1113220585, inf)"

eval_args:
    split: 
        LS: valid_and_test
    mode: full
    group_by: user
    order: TO 
    mode: full