# model name
model_name: BERT

# hidden size
hidden_size: 64

# encoder hidden dimension
num_hidden_layers: 2

# todo: fill
initializer_range: 0.02

# num of head
num_attention_heads: 1

# todo: fill
hidden_dropout_prob: 0.5

# todo: fill
attention_probs_dropout_prob: 0.5

# todo: fill
hidden_act: gelu