# path to train data directory
train_dir: ../data/train/
# path to eval data directory
eval_dir: ../data/eval/
# path to output directory
output_dir: output/

# train data file name
train_file: train_ratings.csv
title_file: titles.tsv
year_file: years.tsv
writer_file: writers.tsv
genre_file: genres.tsv
director_file: directors.tsv

# eval data file name
eval_file: sample_submission.csv