# path to train data directory
train_dir: configs/data/train/
# path to eval data directory
eval_dir: configs/data/eval/
# path to output directory
output_dir: configs/output/

# train data file name
train_file: train_ratings.csv
# eval data file name
eval_file: sample_submission.csv